### ISSUE TITLE
Request to share schematic

### ISSUE THREAD

**Issue by Jianan-Li** [mcer12/Temper-ESP8266#1]
Would you be willing to share the schematic for this project? Thanks for your consideration!

**Comment by mcer12** [comment]
Thanks for the interest in the project, I will make sure to add the schematic asap. Will notify you in this issue once that's done.

**Comment by mcer12** [comment]
Schematic added :) Sorry I took a bit longer with it, I had to redraw it as the original one was a mess and this one resembles pcb layout a bit better. Hopefully I didn't make any errors... if you find anything questionable in it, let me know.

**Comment by moosepants** [comment]
Hey I see you added the schematic PDF and gerbers... is it too much to ask for the CAD versions? I really like this project, but would like to make a couple of tweaks (e.g. replace the reset button with an IR Prox sensor) before I send to PCB fab...

**Comment by mcer12** [comment]
@moosepants I made this in EasyEDA, here's the source. Let me know if you have issues viewing it but it should be public and ready to clone.
https://bit.ly/2PoQ4QE

**Comment by mcer12** [comment]
And don't forget to take a look at design suggestions on wiki page if you plan on tinkering with the design ;)

**Comment by moosepants** [comment]
Thanks very much! I saw the wiki page and will make the suggested updates.  Cheers 👍
