### ISSUE TITLE
Feature request : uMQTT broker

### ISSUE THREAD

**Issue by happytm** [mcer12/Temper-ESP8266#2]
This is stunning hardware and software combination. It would be even better if excellent uMQTT broker is implemented on the device itself so we can access sensor data by using just MQTT Dash app from smartphone. This eliminate need for cloud MQTT broker or local linux device to host MQTT broker. Links are below:

original library:
https://github.com/martin-ger/uMQTTBroker

My implementation simple IOT network using above library:
https://github.com/happytm/BatteryNode

Android App to view sensor data:
https://play.google.com/store/apps/details?id=net.routix.mqttdash&hl=en_US

Thanks.

**Comment by mcer12** [comment]
Hi @happytm If I understand this correctly, it would mean for the device to stay always ON as a broker and to respond to any potential request from the app. That would drop battery life from months to just a few hours. So for this device, it doesn't make much sense. Or did you have something else in mind?

**Comment by happytm** [comment]
If you look at my repository there are 2 sketches. One is called ProbeReceiver.ino which is master for whole network and it has to be mains powered.I would like to use uMQTT broker on this master device. Rest of the devices uses ProbeSender.ino sketch and they are battery powered. These devices send data to master device even without connecting to it. With these devices it takes only between 50 to 60 milliseconds to send data to master and master is passing this data via uMQTT broker to MQTT Dash app mentioned above. I tried to create most power efficient, cost effective and simplest IOT network using ESP8266 devices and I have not yet come across any IOT network which can do all of these. I tried ESPNow protocol but it can not use the protocol and wifi together. I also tried LORA network but it is not simple or cost effective. Please try it using 2 esp8266 devices - one master and one slave - to realize the potential. One thing my code missing is nice user interface you have and I was hoping to use it for my project. 

Thanks.

**Comment by mcer12** [comment]
I don't see why it wouldn't work with uMQTT broker just like any other MQTT broker. What are the reasons you don't just use MQTT? The sketch in the link seems rather complicated.

**Comment by happytm** [comment]
Yes the sketch looks complicated but it uses lot of serial debugging code for newbies like me. ProbeReceiver code also has person tracker code which track and locate the person based on smart phone they use and also code for sending commands to slave which can be removed for only one way communication from slaves to master.For Probesender code it has code most of the which is for receiving commands from master and automatic OTA update both of which are not required for only one way communication from slaves to master. That's the reason I wanted to have nice UI so user can just upload .bin files provided and set all variable required using UI. I wanted truly standalone network so it can be totally local without requiring any real wifi access point or internet connection for local control and at the same time accessible from anywhere in the world using MQTT client app on smartphone if internet is available at the network location.

Thanks.

**Comment by mcer12** [comment]
I see... Well I made this as a MQTT device because I use MQTT myself. I won't be implementing other protocols / platforms unless I personally migrate to them, hope you understand. If you would like to contribute, I will gladly accept any PRs. That said, if you find the UI nice, feel free to grab the code and implement it in your project (as long as it's non-commercial ;)

**Comment by happytm** [comment]
Thank you for your response.
